services:
  analysis-env:
    image: mengen123321/dsci310_group3_m1:latest
    ports:
      - "8787:8788"
    volumes:
      - ./data:/home/rstudio/data
      - ./outputs:/home/rstudio/outputs
      - ./reports:/home/rstudio/reports
      - ./rscript_files:/home/rstudio/rscript_files
      - ./Makefile:/home/rstudio/Makefile
      - ./docs:/home/rstudio/docs
      - ./R:/home/rstudio/R
      - ./tests:/home/rstudio/tests
    environment:
      DISABLE_AUTH: "true"
    command: /init
